# ============================================================================
# GR20 Weather Autobot Configuration
# ============================================================================

# --- Debugging & Output ---
debug:
  # Enable/disable debug mode (true/false)
  enabled: true
  # Save raw data files for each report (true/false)
  raw_data_output: true
  # Save debug files (true/false)
  save_debug_files: true
  # Output directory for debug files
  output_directory: output/debug
  # Validate thresholds in reports (true/false)
  threshold_validation: true
  # Compare generated report with previous (true/false)
  comparison_with_report: true

# --- Start date for report generation (YYYY-MM-DD) ---
startdatum: '2025-07-07'

# --- Report Scheduling ---
# Maximum number of dynamic reports per day
max_daily_reports: 3
# Minimum interval (minutes) between dynamic reports
min_interval_min: 60

# --- SMS Configuration ---
sms:
  # Enable/disable SMS sending (true/false)
  enabled: false
  # Mode: 'test' (send to test_number) or 'production' (send to production_number)
  mode: test  # Options: test, production
  # SMS provider: 'seven' or 'twilio'
  provider: seven  # Options: seven, twilio
  # Production recipient number (used if mode=production)
  production_number: '+4917717816897'
  # Test recipient number (used if mode=test)
  test_number: '+4915158450319'
  # --- Seven.io Provider Settings ---
  seven:
    # API key for seven.io (from environment variable SEVEN_API_KEY)
    api_key: ${SEVEN_API_KEY}
    # Sender name/number (max 11 chars for alphanumeric)
    sender: '4916092170813'
  # --- Twilio Provider Settings ---
  twilio:
    # Twilio Account SID (from environment variable TWILIO_ACCOUNT_SID)
    account_sid: ${TWILIO_ACCOUNT_SID}
    # Twilio Auth Token (from environment variable TWILIO_AUTH_TOKEN)
    auth_token: ${TWILIO_AUTH_TOKEN}
    # Sender phone number (from environment variable TWILIO_PHONE_NUMBER)
    from: ${TWILIO_PHONE_NUMBER}

# --- SMTP (E-Mail) Configuration ---
smtp:
  # SMTP server host (e.g. smtp.gmail.com)
  host: smtp.gmail.com
  # SMTP server port (e.g. 587 for TLS)
  port: 587
  # E-Mail subject prefix
  subject: GR20
  # Recipient E-Mail address
  to: henningemmrich@icloud.com
  # Sender E-Mail address (must match SMTP user)
  user: henning.emmrich@gmail.com



# --- Weather Parameter Thresholds ---
thresholds:
  # Cloud cover threshold (%)
  cloud_cover: 90.0
  # Rain amount threshold (mm)
  rain_amount: 0.5
  # Rain probability threshold (%)
  rain_probability: 10.0
  # Temperature threshold (°C)
  temperature: 30.0
  # Thunderstorm probability threshold (%)
  thunderstorm_probability: 10.0
  # Wind speed threshold (km/h)
  wind_speed: 40.0

# --- Dynamic Report Thresholds (Delta) ---
delta_thresholds:
  # Minimum change in rain probability (%) to trigger update
  rain_probability: 10.0
  # Minimum change in temperature (°C) to trigger update
  temperature: 2.0
  # Minimum change in thunderstorm probability (%) to trigger update
  thunderstorm_probability: 10.0
  # Minimum change in wind speed (km/h) to trigger update
  wind_speed: 5.0

# --- Output file for warning messages (InReach) ---
warning_output_file: output/inreach_warnung.txt
