# Weather Email Automation Configuration
# This file contains all configuration parameters for the weather monitoring system

# Debug settings for development and troubleshooting
debug:
  comparison_with_report: true
  enabled: true
  output_directory: output/debug
  raw_data_output: true
  save_debug_files: true
  threshold_validation: true

# Delta thresholds for change detection (when to trigger warnings)
delta_thresholds:
  rain_probability: 1.0
  temperature: 1.0
  thunderstorm_probability: 1.0
  wind_speed: 1.0

# Report frequency and timing settings
max_daily_reports: 4  # Maximum number of reports per day
min_interval_min: 90  # Minimum interval between reports in minutes

# SMS notification settings
sms:
  api_key: ${SEVEN_API_KEY}
  enabled: false # true or false
  mode: production # 'test' or 'production'
  production_number: '+4917717816897'
  provider: seven  # 'seven' or 'twilio'
  # Seven.io configuration
  seven:
    api_key: ${SEVEN_API_KEY}
    sender: '4916092170813'

  # Phone numbers for notifications
  test_number: '+4915158450319'

  # Twilio configuration (alternative provider)
  twilio:
    account_sid: ${TWILIO_ACCOUNT_SID}
    auth_token: ${TWILIO_AUTH_TOKEN}
    from: ${TWILIO_PHONE_NUMBER}

# Email configuration for sending weather reports
smtp:
  host: smtp.gmail.com
  port: 587
  subject: GR20
  to: henningemmrich@icloud.com
  user: henning.emmrich@gmail.com

# Start date for the weather monitoring (YYYY-MM-DD format)
startdatum: '2025-07-07'

# Weather thresholds for triggering alerts
thresholds:
  cloud_cover: 90.0  # Cloud cover percentage
  rain_amount: 0.5   # Rain amount in mm
  rain_probability: 15.0  # Rain probability percentage
  temperature: 25.0  # Temperature in Celsius
  thunderstorm_probability: 10.0  # Thunderstorm probability percentage
  wind_speed: 40.0   # Wind speed in km/h

# Output file for warning messages
warning_output_file: output/inreach_warnung.txt
