# =============================================================================
# WETTERBERICHT-AUTOMATISIERUNG - KONFIGURATION
# =============================================================================
# Vereinfachte Konfiguration mit nur den essentiellen Einstellungen

# =============================================================================
# GRUNDKONFIGURATION
# =============================================================================

# Startdatum der Tour (YYYY-MM-DD Format)
# Set to 14 days ago so today is the last stage (Conca)
startdatum: "2025-06-22"

# =============================================================================
# E-MAIL-KONFIGURATION
# =============================================================================
smtp:
  host: smtp.gmail.com
  port: 587
  user: henning.emmrich@gmail.com
  to: henningemmrich@icloud.com
  subject: GR20

# =============================================================================
# SMS-KONFIGURATION
# =============================================================================
sms:
  enabled: false  # Enable SMS functionality
  provider: twilio  # "seven" oder "twilio"
  mode: "test"  # "test" oder "production"
  
  # Testnummer für Entwicklung und Tests
  test_number: "+4915158450319"
  # Produktionsnummer für echte Berichte
  production_number: "+4917717816897"
  
  # Seven.io Provider Konfiguration
  seven:
    api_key: "${SEVEN_API_KEY}"
    sender: "4916092170813"
  
  # Twilio Provider Konfiguration
  twilio:
    account_sid: "${TWILIO_ACCOUNT_SID}"
    auth_token: "${TWILIO_AUTH_TOKEN}"
    from: "${TWILIO_PHONE_NUMBER}"

# =============================================================================
# RELEVANZ-SCHWELLENWERTE
# =============================================================================
# Ab wann soll ein Wert als "relevant" hervorgehoben werden

thresholds:
  rain_probability: 25.0      # Regenwahrscheinlichkeit in %
  rain_amount: 2.0           # Regenmenge in mm
  thunderstorm_probability: 20.0  # Gewitterwahrscheinlichkeit in %
  wind_speed: 40.0           # Windgeschwindigkeit in km/h (nur für Risikobewertung)
  temperature: 30.0          # Temperatur in °C (nur für Risikobewertung)
  cloud_cover: 50.0          # Bewölkung in %

# =============================================================================
# ÄNDERUNGS-SCHWELLENWERTE
# =============================================================================
# Ab welcher Veränderung soll es eine untertägige Warnung geben

delta_thresholds:
  thunderstorm_probability: 20.0  # Delta für Gewitter in %
  rain_probability: 30.0          # Delta für Regen in %
  wind_speed: 10.0                # Delta für Wind in km/h
  temperature: 2.0                # Delta für Temperatur in °C

# =============================================================================
# VERHALTENS-PARAMETER
# =============================================================================

min_interval_min: 60              # Minimaler Abstand zwischen Warnungen in Minuten
max_daily_reports: 3              # Maximale Anzahl Berichte pro Tag

# =============================================================================
# DEBUG-KONFIGURATION
# =============================================================================
# Debug-Ausgaben für Konsistenzprüfung und Fehleranalyse

debug:
  enabled: true                   # Debug-Ausgaben aktivieren
  raw_data_output: true           # Rohdaten-Ausgabe für jeden Layer
  threshold_validation: true      # Schwellenwert-Validierung
  comparison_with_report: true    # Vergleich Rohdaten vs. Bericht
  save_debug_files: true          # Debug-Dateien speichern
  output_directory: "output/debug" # Verzeichnis für Debug-Dateien

# =============================================================================
# DATEIPFADE
# =============================================================================

state_file: "data/warning_state.json"
warning_output_file: "output/inreach_warnung.txt"
sharemap_url: "https://share.garmin.com/PDFCF" 